"""Add onboarding_state to tenants

Revision ID: 10ff0d79f10c
Revises: 113b7ab1d6de
Create Date: 2026-07-28 19:25:22.335483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10ff0d79f10c'
down_revision: Union[str, None] = '113b7ab1d6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('onboarding_state', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'onboarding_state')
    # ### end Alembic commands ###

