"""add is_locked to user

Revision ID: 113b7ab1d6de
Revises: 857fc4d21db8
Create Date: 2026-07-28 17:21:29.192959
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '113b7ab1d6de'
down_revision: Union[str, None] = '857fc4d21db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###

