"""add_stripe_fields

Revision ID: 1d09e76ff11e
Revises: e5e4229e7ba2
Create Date: 2026-07-28 14:29:45.149152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d09e76ff11e'
down_revision: Union[str, None] = 'e5e4229e7ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan_tier', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_column('tenants', 'plan_tier')
    # ### end Alembic commands ###

