"""Add phone_number to user

Revision ID: 8446f9834fe7
Revises: 71b4b2c7c8f5
Create Date: 2026-07-27 15:33:13.904235
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '8446f9834fe7'
down_revision: str | None = '71b4b2c7c8f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###

