"""add status to tenant

Revision ID: 857fc4d21db8
Revises: 1d09e76ff11e
Create Date: 2026-07-28 17:11:47.750849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '857fc4d21db8'
down_revision: Union[str, None] = '1d09e76ff11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'status')
    # ### end Alembic commands ###

