"""auto

Revision ID: e5e4229e7ba2
Revises: 89e9544e5d05
Create Date: 2026-07-28 13:04:58.868836
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5e4229e7ba2'
down_revision: Union[str, None] = '89e9544e5d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('platform', sa.String(length=20), nullable=False))
    op.drop_column('invitations', 'role')
    op.add_column('users', sa.Column('platform', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform')
    op.add_column('invitations', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('invitations', 'platform')
    # ### end Alembic commands ###

